### ISSUE TITLE
App crash when editing budget.

### ISSUE THREAD

**Issue by jamessolo12** [dsolonenko/financisto#153]
App crashes when editing budget on Android 11.

I have had a budget for a long time, that seems to be significant.
1. Goto budgets screen
2. Long press on budget
3. Click Edit
4. --Crash--

I've tried creating a new budget on a new install on a separate phone and that doesn't have the same effect.

 

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.orangesoftware.financisto, PID: 
    java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.orangesoftware.financisto/ru.orangesoftware.financisto.activity.BudgetActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(int)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

``````

     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(int)' on a null object reference
        at ru.orangesoftware.financisto.activity.MyEntitySelector.clearSelection(MyEntitySelector.java:161)
        at ru.orangesoftware.financisto.activity.MyEntitySelector.fillCheckedEntitiesInUI(MyEntitySelector.java:198)
        at ru.orangesoftware.financisto.activity.BudgetActivity.editBudget(BudgetActivity.java:160)
        at ru.orangesoftware.financisto.activity.BudgetActivity.onCreate(BudgetActivity.java:131)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
```

**Comment by jamessolo12** [comment]
This may have already been fixed, although I can't find a related issue. I checked out the current code from github and it no longer occurs. Could just need a new version released to live.

**Comment by jamessolo12** [comment]
Duplicate:
https://github.com/dsolonenko/financisto/issues/112
